# Generated by Django 4.2.4 on 2023-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='عنوان سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس سایت')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(max_length=200, null=True, verbose_name='فکس سایت')),
                ('email', models.TextField(null=True, verbose_name='ایمیل سایت')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما سایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوگو سایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی ')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات ',
            },
        ),
    ]
