# Generated by Django 4.2.4 on 2023-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='text_welcome',
            field=models.CharField(max_length=200, null=True, verbose_name='آدرس سایت'),
        ),
    ]
