# Generated by Django 4.2.4 on 2023-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_site_setting_text_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_setting',
            name='text_welcome',
            field=models.CharField(max_length=200, null=True, verbose_name='متن خوشامد گویی'),
        ),
    ]
