# Generated by Django 4.2.4 on 2023-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_footerlinkboxmodel_footerlinkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinkboxmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerlinkmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerlinkmodel',
            name='url',
            field=models.URLField(max_length=500, verbose_name='لنیک'),
        ),
    ]
