# Generated by Django 4.2.4 on 2023-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی ')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان ')),
                ('data_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان')),
                ('See_message', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('message', models.TextField(verbose_name='متن پیام کاربر')),
                ('Answer_admin', models.TextField(null=True, verbose_name='متن پیام ادمین')),
            ],
            options={
                'verbose_name': 'صفحه تماس با ما',
                'verbose_name_plural': 'تماس با ما سایت',
            },
        ),
    ]
