# Generated by Django 4.2.4 on 2023-08-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0002_article_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 25), verbose_name='تاریخ مقاله'),
            preserve_default=False,
        ),
    ]
