# Generated by Django 4.2.4 on 2023-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='about_background_img',
            field=models.ImageField(null=True, upload_to='images/about_page/background_img', verbose_name='پس ضمینه ی  درباره ما'),
        ),
    ]
